name: task_api_rest_server
description: REST API server for task management in Dart
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_cors_headers: ^0.1.5
  uuid: ^4.0.0
  args: ^2.4.0
  
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0