server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: task-api-server
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.taskapi: DEBUG
    org.springframework.web: INFO