source 'https://rubygems.org'

gem 'sinatra', '~> 3.1'
gem 'sinatra-contrib', '~> 3.1'
gem 'puma', '~> 6.4'
gem 'json', '~> 2.7'
gem 'securerandom'
gem 'time'
gem 'rackup', '~> 2.1'

group :development do
  gem 'rerun', '~> 0.14'
end