name:                task-grpc-client
version:             0.1.0.0
github:              "cloudstreet-dev/REST-gRPC-in-33-Languages"
license:             MIT
author:              "David Christian Liedle"
maintainer:          "david.liedle@gmail.com"
copyright:           "2024 David Christian Liedle"

description:         Task Management gRPC Client in Haskell

dependencies:
- base >= 4.7 && < 5
- grpc-haskell
- grpc-haskell-core
- proto3-suite
- proto3-wire
- text
- time
- uuid
- bytestring
- containers

executables:
  task-grpc-client:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall