name: task_api_rest_client
description: REST API client for task management in Dart
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0