name = "task_server"
version = "1.0.0"

[dependencies]
gleam_stdlib = "~> 0.34"
gleam_http = "~> 3.5"
gleam_json = "~> 1.0"
mist = "~> 1.0"
gleam_erlang = "~> 0.25"
gleam_otp = "~> 0.10"

[dev-dependencies]
gleeunit = "~> 1.0"