name: task_api_grpc_server
description: gRPC server for task management in Dart
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  grpc: ^3.2.0
  protobuf: ^3.0.0
  uuid: ^4.0.0
  
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0