name = "task_client"
version = "1.0.0"

[dependencies]
gleam_stdlib = "~> 0.34"
gleam_http = "~> 3.5"
gleam_httpc = "~> 2.1"
gleam_json = "~> 1.0"
gleam_erlang = "~> 0.25"

[dev-dependencies]
gleeunit = "~> 1.0"