name: Deploy Book

on:
  push:
    branches: [ main ]
    paths:
      - 'book/**'
      - '.github/workflows/deploy-book.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          npm install -g @honkit/honkit
          npm install -g gitbook-plugin-*
      
      - name: Build book
        run: |
          cd book
          # Create a simple index.html if not exists
          if [ ! -f "index.html" ]; then
            cat > index.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
              <title>REST & gRPC in 33 Languages</title>
              <meta charset="utf-8">
              <style>
                  body { font-family: system-ui; max-width: 800px; margin: 0 auto; padding: 20px; }
                  h1 { color: #333; }
                  .chapters { list-style: none; padding: 0; }
                  .chapters li { margin: 10px 0; }
                  .chapters a { color: #0066cc; text-decoration: none; }
                  .chapters a:hover { text-decoration: underline; }
              </style>
          </head>
          <body>
              <h1>REST & gRPC in 33 Languages</h1>
              <p>A comprehensive guide to building REST and gRPC APIs in 33 programming languages.</p>
              
              <h2>Table of Contents</h2>
              <ul class="chapters">
          EOF
          
          # Add links to all chapters
          for chapter in manuscript/chapters/*.md; do
            basename=$(basename "$chapter" .md)
            echo "<li><a href=\"manuscript/chapters/$basename.html\">Chapter ${basename}</a></li>" >> index.html
          done
          
          cat >> index.html <<EOF
              </ul>
              
              <h2>Resources</h2>
              <ul>
                  <li><a href="https://github.com/cloudstreet-dev/REST-gRPC-in-33-Languages">GitHub Repository</a></li>
                  <li><a href="../README.md">README</a></li>
                  <li><a href="../LEARNING_PATH.md">Learning Path</a></li>
              </ul>
          </body>
          </html>
          EOF
          fi
          
          # Convert markdown to HTML
          for chapter in manuscript/chapters/*.md; do
            basename=$(basename "$chapter" .md)
            pandoc "$chapter" -o "manuscript/chapters/${basename}.html" \
              --standalone \
              --toc \
              --highlight-style=github \
              --css=https://cdn.jsdelivr.net/npm/github-markdown-css/github-markdown.min.css \
              || echo "Pandoc not available, using basic conversion"
          done
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'book'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  create-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    steps:
      - uses: actions/checkout@v3
      
      - name: Create PDF
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex
          
          cd book
          pandoc manuscript/chapters/*.md \
            -o "REST-gRPC-in-33-Languages.pdf" \
            --pdf-engine=xelatex \
            --toc \
            --toc-depth=2 \
            --highlight-style=github
      
      - name: Create EPUB
        run: |
          cd book
          pandoc manuscript/chapters/*.md \
            -o "REST-gRPC-in-33-Languages.epub" \
            --toc \
            --toc-depth=2 \
            --epub-cover-image=cover.png \
            --highlight-style=github
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            book/REST-gRPC-in-33-Languages.pdf
            book/REST-gRPC-in-33-Languages.epub
          body: |
            # REST & gRPC in 33 Languages
            
            This release includes:
            - Complete book with all 33 chapters
            - Code examples for all languages
            - Universal test suite
            - Performance benchmarks
            - Docker support
            
            ## Downloads
            - 📖 [PDF Version](REST-gRPC-in-33-Languages.pdf)
            - 📱 [EPUB Version](REST-gRPC-in-33-Languages.epub)
            - 💻 [Online Version](https://cloudstreet-dev.github.io/REST-gRPC-in-33-Languages/)
            
            ## What's New
            - All 33 language implementations complete
            - gRPC support for 20+ languages
            - Comprehensive testing framework
            - Performance benchmarking suite
            - Docker Compose configuration
            - Interactive quick-start script
            - Learning path guide